### ISSUE TITLE
Chicken Farms Not Working

### ISSUE THREAD

**Issue by QRMboi** [TheFlash787/Mobpression#5]
First off, want to say the mod works great right off the bat, it single handily killed the lag that was happening on my community server when certain players were at their bases. The unfortunate part is I installed it to help facilitate the lag with chicken farms, but each stack only acts as one chicken. Testing it out, a player of mine has 150 chickens, between 6 chickens with an average of 30ish. These stacks only drop an average egg of one chicken. I really love this mod cause it kills lag, but it kills my players chicken farms too. Is this something that can be fixed?

**Comment by TheFlash787** [comment]
That's interesting. I notice it is quite counter-intuitive. You are able to blacklist a mob-id from being compressed. Which means that you could stop the chickens from being compressed entirely. Or I have a current development build which allows you to select a minimum amount of mobs that need to be touching, in order to compress. i.e. if you set the threshold to 3, they will only compress when three of them are touching at one time. By default, they compress as soon as one touches another. However that would take effect on all mobs in the server.

However, it's definitely difficult because we know that player doesn't necessarily need 150 chickens all in one coop. Was the lag you were experiencing before due to that player's chicken setup? (If it wasn't, perhaps disabling compression for just the chickens (and/or any productive animal) could be the best option)

Sorry for the delay, also!

**Comment by TheFlash787** [comment]
Here is an updated jar file which contains the ability to add a minimum threshold for compression. **In the future**, I could look into actually producing item drops, based on the amount of compressed mobs there are. (i.e. if you have a 5x chicken, the chicken will drop 5x the amount of eggs)
[Mobpression.zip](https://github.com/TheFlash787/Mobpression/files/3537255/Mobpression.zip)

**Comment by TheFlash787** [comment]
Hey! Please use this version instead: 
[Mobpression-Fixed.zip](https://github.com/TheFlash787/Mobpression/files/3561005/Mobpression-Fixed.zip)

**Comment by QRMboi** [comment]
Sorry, I didn't see the posts on the day you initially replied to me with till I got this one through. I'll give this version a go on my server and see how it works and close this topic if things go well. Thank you c: 

The lag actually subsided after I took out the compression mod and then killed all the chickens, then replaced them, like maybe the chickens were getting stuck in some geometry and adding lag. But the compression either way would help circumvent that issue from starting in the first place, hopefully. 

Thanks for your work!
