### ISSUE TITLE
Could not pass the event CollideEntityEvent$Impl to an Event Listener

### ISSUE THREAD

**Issue by runescapejon** [TheFlash787/Mobpression#6]
**Describe the bug**
Not sure what happen here but i installed the plugin and saw this error spamming https://pastebin.com/raw/8uq2pJad
I am using Mobpression-1.0.2-SNAPSHOT
and 
spongeforge-1.12.2-2825-7.1.7-RC3770

**Expected behavior**

**Screenshots**

**Plugin Version:**
*e.g. Mobpression 1.0.2-SNAPSHOT*

**Additional context**

**Comment by TheFlash787** [comment]
Hey! This should now have been fixed in [this version](https://github.com/TheFlash787/Mobpression/files/3560367/Mobpression.zip). I will be uploading this build to Ore soon which should also fix other issues which may be lingering for certain players. 

Another change that is bought with this build is that you can now specify a minimum amount of mobs required for compression alongside the feature to blacklist certain mobs (incase you were having issues with farm-mobs compressing.) However I mentioned [here](https://github.com/TheFlash787/Mobpression/issues/5#issuecomment-524552373) that I could work around that by allowing mobs to drop <compressed>X amount of mob drops compared to normal.

Anywho. Let us know how that goes! Thank you. ❤️
