### ISSUE TITLE
Could not pass the event FMLServerStartedEvent to an Event Listener

### ISSUE THREAD

**Issue by Corcustos** [TheFlash787/Mobpression#7]
**Describe the bug**
Along with the plugin spitting [this error](https://pastebin.com/L7isRcwS) into console, it also does not generate a config. Generates a blank folder with no config inside. Plugin does not function on my versions with bare minimum installed.

**Plugin Version:**
Mobpression 1.0.3-SNAPSHOT (Provided in another issue report)

**Additional Info**
SF 1.12.2-2825-7.1.6
Forge 1.12.2-14.23.5.2838

**Comment by TheFlash787** [comment]
[Mobpression-Fixed.zip](https://github.com/TheFlash787/Mobpression/files/3561003/Mobpression-Fixed.zip)
Hey @Corcustos ! Thank you for reporting this. There appears to have been an issue with the database-creation in the plugin. This has now been fixed in this jar. This will be pushed to Ore in the upcoming days too. Thank you!
